# Generated by Django 4.0.2 on 2022-02-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_banner_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner_Image',
            new_name='Banner',
        ),
    ]
