# Generated by Django 4.0.2 on 2022-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_banner_image_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='image',
            field=models.ImageField(default='', upload_to='screenshots/images'),
        ),
    ]
